nav:
    - Introduction: Deep-learning-book.md
    - Artificial-neural-network: Artificial-neural-network.md
    - Part-I-Applied-Math-and-Machine-Learning-Basics: Part-I-Applied-Math-and-Machine-Learning-Basics
    - Part-II-Deep-Networks-Modern-Practices: Part-II-Deep-Networks-Modern-Practices
 