nav:
    - Introduction: index.md
    # 深度学习的理论知识    
    - Deep-learning: Deep-learning
    - Feature-engineering: Feature-engineering
    - Machine-learning: Machine-learning
    - Data-generating-process: Data-generating-process.md
    - VS-statistical-model-VS-machine-learning-model: VS-statistical-model-VS-machine-learning-model.md
    - VS-statistics-model-VS-stochastic-process: VS-statistical-model-VS-stochastic-process.md