edit_uri: ''
extra_css:
- css/extra.css
google_analytics:
- UA-27795084-5
- mkdocs.org
markdown_extensions:
- toc:
    permalink: '#'
nav:
- Home: index.md
- AI-meeting: AI-meeting.md
- AI-papers: AI-papers.md
- Research-Institution&Researcher:
  - Researcher: Research-Institution&Researcher/Researcher.md
  - Research-institution: Research-Institution&Researcher/Research-institution.md
- Theory:
  - Introduction: Theory/index.md
  - Probability-theory-and-Statistics:
    - Introduction: Theory/Probability-theory-and-Statistics/index.md
    - Probability-theory:
      - Probability-theory: Theory/Probability-theory-and-Statistics/Probability-theory/Probability-theory.md
      - Stochastic-process:
        - Stochastic-process: Theory/Probability-theory-and-Statistics/Probability-theory/Stochastic-process/Stochastic-process.md
        - Markov-chain: Theory/Probability-theory-and-Statistics/Probability-theory/Stochastic-process/Markov-chain.md
        - Independent-and-identically-distributed-random-variables: Theory/Probability-theory-and-Statistics/Probability-theory/Stochastic-process/Independent-and-identically-distributed-random-variables.md
    - Statistics:
      - Introduction: Theory/Probability-theory-and-Statistics/Statistics/index.md
      - Statistics: Theory/Probability-theory-and-Statistics/Statistics/Statistics.md
      - Statistical-inference: Theory/Probability-theory-and-Statistics/Statistics/Statistical-inference.md
      - Statistical-model: Theory/Probability-theory-and-Statistics/Statistics/Statistical-model.md
      - VS-statistical-interference-VS-descriptive-statistics: Theory/Probability-theory-and-Statistics/Statistics/VS-statistical-interference-VS-descriptive-statistics.md
  - Deep-learning:
    - Book-deep-learning:
      - Introduction: Theory/Deep-learning/Book-deep-learning/Deep-learning-book.md
      - Chapter-1-Introduction: Theory/Deep-learning/Book-deep-learning/Chapter-1-Introduction.md
      - Artificial-neural-network: Theory/Deep-learning/Book-deep-learning/Artificial-neural-network.md
      - Chapter-5-Machine-Learning-Basics:
        - Chapter-5-Machine-Learning-Basics: Theory/Deep-learning/Book-deep-learning/Chapter-5-Machine-Learning-Basics/Chapter-5-Machine-Learning-Basics.md
        - Task:
          - Pattern-recognition: Theory/Deep-learning/Book-deep-learning/Chapter-5-Machine-Learning-Basics/Task/Pattern-recognition.md
          - Sequence-labeling:
            - Sequence-labeling: Theory/Deep-learning/Book-deep-learning/Chapter-5-Machine-Learning-Basics/Task/Sequence-labeling/Sequence-labeling.md
            - Sequence-Labeling-Generative-and-Discriminative: Theory/Deep-learning/Book-deep-learning/Chapter-5-Machine-Learning-Basics/Task/Sequence-labeling/Sequence-Labeling-Generative-and-Discriminative.md
        - 5.2-Capacity-Overfitting-and-Underfitting: Theory/Deep-learning/Book-deep-learning/Chapter-5-Machine-Learning-Basics/5.2-Capacity-Overfitting-and-Underfitting.md
    - End-to-end:
      - Introduction: Theory/Deep-learning/End-to-end/End-to-end.md
      - End-to-end-reinforcement-learning: Theory/Deep-learning/End-to-end/wikipedia-End-to-end-reinforcement-learning.md
    - Attention:
      - Papers: Theory/Deep-learning/Attention/Papers.md
  - Feature-engineering:
    - Data-transformation(statistics): Theory/Feature-engineering/Data-transformation(statistics).md
    - Feature-scaling: Theory/Feature-engineering/Feature-scaling.md
    - Normalization(statistics): Theory/Feature-engineering/Normalization(statistics).md
  - Markov-model:
    - Markov-chain: Theory/Markov-model/Markov-chain.md
    - Markov-models: Theory/Markov-model/Markov-models.md
    - Hidden-Markov-model: Theory/Markov-model/Hidden-Markov-model.md
    - Viterbi-algorithm: Theory/Markov-model/Viterbi-algorithm.md
    - Forward-algorithm: Theory/Markov-model/Forward-algorithm.md
  - CRF:
    - CRF: Theory/CRF/crf.md
  - Data-generating-process: Theory/Data-generating-process.md
  - VS-statistical-model-VS-machine-learning-model: Theory/VS-statistical-model-VS-machine-learning-model.md
  - VS-statistics-model-VS-stochastic-process: Theory/VS-statistical-model-VS-stochastic-process.md
- Programming:
  - Model-And-layer-And-computation-And-computational-graph: Programming/Model-And-layer-And-computation-And-computational-graph.md
  - Programming-paradigm-of-deep-learning: Programming/Programming-paradigm-of-deep-learning.md
  - VS-pytorch-vs-tensorflow: Programming/VS-pytorch-vs-tensorflow.md
- Data-set:
  - Introduction: Data-set/index.md
- Application:
  - NLP: Application/NLP.md
  - Computable-knowledge:
    - Introduction: Application/Computable-knowledge/Knowledge-representation-and-reasoning.md
plugins:
- search
repo_url: https://github.com/dengking/machine-learning
site_author: DengKing
site_description: Project documentation with Markdown.
site_name: machine-learning
site_url: https://dengking.github.io/machine-learning
theme:
  name: material
