nav:
    - Introduction: index.md
    - Back-Propagation: Back-Propagation
    - 6.5-Back-Propagation-and-Other-Differentiation: 6.5-Back-Propagation-and-Other-Differentiation.md
    - Implementation: Implementation.md
    - Backpropagation-through-time: Backpropagation-through-time.md
    