nav:    
    - Neural-Networks-Tutorial: Neural-Networks-Tutorial.md
    - Computation-And-model-And-computational-graph: Computation-And-model-And-computational-graph.md
    - Model-capacity: Model-capacity
    - Model-initialization: Model-initialization
    - Batch-epoch-step: Batch-epoch-step
    - Activation-function: Activation-function
    - Design-neural-network: Design-neural-network.md