nav:
    - Task-of-NLP: Task-of-NLP.md
    - Entity-Linking: Entity-Linking
    - Named-entity-recognition: Named-entity-recognition
    - Relationship-Extraction: Relationship-Extraction
    - Shallow-parsing: Shallow-parsing
    - Text-Classification: Text-Classification
    - Part-of-speech-tagging: Part-of-speech-tagging
    - Neural-machine-translation: Neural-machine-translation
    - Distant-supervision: Distant-supervision