nav:
    - Task-of-NLP: Task-of-NLP.md
    - Entity-Linking: Entity-Linking
    - Named-entity-recognition: Named-entity-recognition
    - Relationship-Extraction: Relationship-Extraction
    - Shallow-syntax: Shallow-syntax
    - Text-Classification: Text-Classification