nav:
    - Text-Classification: Text-Classification.md
    - paper-Bidirectional-LSTM-with-attention-mechanism-and-convolutional-layer: paper-Bidirectional-LSTM-with-attention-mechanism-and-convolutional-layer.md