nav:
    - Artificial-neural-network: Artificial-neural-network.md
    - Neural-Networks-Tutorial: Neural-Networks-Tutorial.md
    - ujjwalkarn-A-Quick-Introduction-to-Neural-Networks: ujjwalkarn-A-Quick-Introduction-to-Neural-Networks.md