nav:
    - Introduction: Deep-learning-book.md
    - Chapter-1-Introduction: Chapter-1-Introduction.md
    - Artificial-neural-network: Artificial-neural-network.md
    - Chapter-5-Machine-Learning-Basics: Chapter-5-Machine-Learning-Basics