nav:    
    - Part-II-Deep-Networksb-Modern-Practice: Part-II-Deep-Networksb-Modern-Practice.md
    - 6-Deep-Feedforward-Networks: 6-Deep-Feedforward-Networks
    - 7-Regularization-for-Deep-Learning: 7-Regularization-for-Deep-Learning
    - 8-Optimization-for-Training-Deep-Models: 8-Optimization-for-Training-Deep-Models
    - 9-Convolutional-Networks: 9-Convolutional-Networks
    - 10-Sequence-Modeling-Recurrent-and-Recursive-Nets: 10-Sequence-Modeling-Recurrent-and-Recursive-Nets
    - 12-Applications: 12-Applications
