nav:    
    - Part-II-Deep-Networksb-Modern-Practice: Part-II-Deep-Networksb-Modern-Practice.md
    - 6.5-Back-Propagation-and-Other-Differentiation-algorithms: 6.5-Back-Propagation-and-Other-Differentiation-algorithms