nav:    
    - 6-Deep-Feedforward-Network: 6-Deep-Feedforward-Network.md
    - 6.2-Gradient-Based-Learning: 6.2-Gradient-Based-Learning.md
    - 6.4-Architecture-Design: 6.4-Architecture-Design
    - 6.5-Back-Propagation-and-Other-Differentiation-algorithms: 6.5-Back-Propagation-and-Other-Differentiation-algorithms
    - Activation-function: Activation-function
    