nav:
    - Programming-paradigm: Programming-paradigm
    - TensorFlow: TensorFlow
    - pytorch: pytorch
    - Keras: Keras
    - VS-pytorch-vs-tensorflow: VS-pytorch-vs-tensorflow.md
    - NumFocus: NumFocus
    