nav:
    - Home: index.md
    - AI-meeting: AI-meeting.md
    - AI-papers: AI-papers.md
    - Research-Institution&Researcher: Research-Institution&Researcher
# 理论知识    
    - Theory: Theory
# 实现，主要介绍software    
    - Programming: Programming
# 数据集    
    - Data-set: Data-set
# 应用领域    
    - Application: Application