nav:
    - Primer: Primer.md
    - Stochastic-process: Stochastic-process.md
    - Markov-chain: Markov-chain.md
    - Independent-and-identically-distributed-random-variables: Independent-and-identically-distributed-random-variables.md